### ISSUE TITLE
kam.conf is not updated to default version on install

### ISSUE THREAD

**Issue by jgeudens** [pluyckx/kam#10]
## Situation:
Fresh install of 1.1.0-beta1
Change conf file
Run install again

**Result**: Configuration is backed up to kam.conf.back. But kam.conf isn't changed back to default configuration.

Is this normal behavior?

**Comment by pluyckx** [comment]
I'll have a look at it. Normally a backup is made and then the default config is copied and used. Maybe the default isn't copied back because the version is the same.
